# Generated by Django 5.2 on 2025-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_musicasalva_imagem_musicasalva_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicasalva',
            name='imagem',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='musicasalva',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
