# Generated by Django 5.2 on 2025-06-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_musicasalva_curtida_playlist_playlist_curtir'),
        ('musica', '0005_alter_musicasalva_imagem_alter_musicasalva_link'),
    ]

    operations = [
    ]
