# Generated by Django 5.2 on 2025-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_profile_privacidade_seguidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagem_perfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
