# Generated by Django 5.2 on 2025-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_nascimento_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
