# Generated by Django 5.2 on 2025-06-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_profile_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagem_perfil_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
