# Generated by Django 5.2 on 2025-05-06 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0006_community_nome_tag_alter_community_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='nome_tag',
            field=models.CharField(max_length=105, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
