# Generated by Django 5.2 on 2025-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0007_community_profile_picture_alter_community_nome_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
