# Generated by Django 5.2 on 2025-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0008_alter_community_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
