# Generated by Django 5.2 on 2025-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0011_alter_community_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
