# Generated by Django 5.2 on 2025-05-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0015_community_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='admin',
            new_name='criador',
        ),
    ]
