# Generated by Django 5.2 on 2025-06-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0017_post'),
        ('musica', '0003_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='musica',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='musica.musicasalva'),
            preserve_default=False,
        ),
    ]
