# Generated by Django 5.2 on 2025-06-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0018_post_musica'),
        ('musica', '0003_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='musica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musica.musicasalva'),
        ),
    ]
