# Generated by Django 5.2 on 2025-06-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0019_post_curtidores_delete_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='curtidores',
            field=models.ManyToManyField(related_name='curtidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
