# Generated by Django 5.2 on 2025-06-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0020_alter_post_curtidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
