# Generated by Django 5.2 on 2025-06-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0019_alter_post_musica'),
        ('comunidade', '0020_alter_post_curtidores'),
    ]

    operations = [
    ]
