# Generated by Django 5.2 on 2025-06-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0020_alter_post_curtidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
    ]
