# Generated by Django 5.2 on 2025-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0021_alter_community_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.URLField(blank=True, default='sapuca-Te78u8ZzqcKnrSdbtrhCNnMug4aV9o.jpg', null=True),
        ),
    ]
