# Generated by Django 5.2 on 2025-06-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0021_merge_20250604_1302'),
        ('comunidade', '0025_alter_community_profile_picture_hash'),
    ]

    operations = [
    ]
