# Generated by Django 5.2 on 2025-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0026_merge_20250610_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://tfavf9hmcaamd4yg.public.blob.vercel-storage.com/b4864697-cf52-4e20-a2d1-ebbd3b8a3a5c.jpg', null=True),
        ),
    ]
