# Generated by Django 5.2 on 2025-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0021_remove_post_curtidas'),
        ('comunidade', '0027_alter_community_profile_picture'),
    ]

    operations = [
    ]
